/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description C端用户注册
         */
        post: operations["register_user_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login User
         * @description C端用户登录
         */
        post: operations["login_user_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories
         * @description 获取所有试卷分类列表 (按 sort_order 升序)
         */
        get: operations["get_categories_api_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exams
         * @description C端查询试卷列表 (标准分页)
         */
        get: operations["list_exams_api_v1_exams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exams/{exam_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Detail
         * @description C端获取试卷详情 (含试卷题目)
         */
        get: operations["get_exam_detail_api_v1_exams__exam_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Exam
         * @description 开始答题：生成唯一 record_id，并自动被动结算历史超期记录
         */
        post: operations["start_exam_api_v1_records_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Exam
         * @description 提交答卷：支持 5 分钟宽限期 Token 验证与悲观锁抢提交防护
         */
        post: operations["submit_exam_api_v1_records_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{record_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Report
         * @description 获取答题成绩分析报告 (含得分统计、错题解析、收藏状态)
         */
        get: operations["get_exam_report_api_v1_records__record_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam History
         * @description 获取个人答题历史明细 (标准分页)
         */
        get: operations["get_exam_history_api_v1_records_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Favorites
         * @description 获取用户收藏题目列表 (标准分页)
         */
        get: operations["list_favorites_api_v1_favorites_get"];
        put?: never;
        /**
         * Add Favorite
         * @description 添加题目到收藏夹
         */
        post: operations["add_favorite_api_v1_favorites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Favorite
         * @description 取消收藏题目
         */
        delete: operations["remove_favorite_api_v1_favorites__question_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Admin
         * @description B端管理员登录
         */
        post: operations["login_admin_api_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Init Super Admin
         * @description 初始化超级管理员 (仅在无管理员时可调用)
         */
        post: operations["init_super_admin_api_v1_admin_auth_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Questions
         * @description B端获取题目列表 (标准分页 + 条件筛选)
         */
        get: operations["list_questions_api_v1_admin_questions_get"];
        put?: never;
        /**
         * Create Question
         * @description B端创建题目
         */
        post: operations["create_question_api_v1_admin_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Question
         * @description B端编辑修改题目
         */
        put: operations["update_question_api_v1_admin_questions__question_id__put"];
        post?: never;
        /**
         * Delete Question
         * @description B端删除题目
         */
        delete: operations["delete_question_api_v1_admin_questions__question_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/questions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Questions Excel
         * @description B端 Excel 导入题目 (支持列: 题型, 题干, 选项A, 选项B, 选项C, 选项D, 答案, 解析, 难度)
         */
        post: operations["import_questions_excel_api_v1_admin_questions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Exams
         * @description B端试卷列表查询
         */
        get: operations["list_admin_exams_api_v1_admin_exams_get"];
        put?: never;
        /**
         * Create Exam
         * @description B端创建试卷与进行关联组卷
         */
        post: operations["create_exam_api_v1_admin_exams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exams/{exam_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Exam
         * @description B端修改编辑试卷配置与重新组卷
         */
        put: operations["update_exam_api_v1_admin_exams__exam_id__put"];
        post?: never;
        /**
         * Delete Exam
         * @description B端删除试卷
         */
        delete: operations["delete_exam_api_v1_admin_exams__exam_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Admin Categories
         * @description B端获取全量分类列表
         */
        get: operations["list_admin_categories_api_v1_admin_categories_get"];
        put?: never;
        /**
         * Create Category
         * @description B端创建分类
         */
        post: operations["create_category_api_v1_admin_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Category
         * @description B端修改分类
         */
        put: operations["update_category_api_v1_admin_categories__category_id__put"];
        post?: never;
        /**
         * Delete Category
         * @description B端删除分类
         */
        delete: operations["delete_category_api_v1_admin_categories__category_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description B端获取注册 C端用户列表
         */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Records
         * @description B端获取全站用户答题明细列表 (标准分页)
         */
        get: operations["list_all_records_api_v1_admin_users_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description B端图片/文件上传
         */
        post: operations["upload_file_api_v1_admin_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminExamRecordResponse */
        AdminExamRecordResponse: {
            /** Record Id */
            record_id: number;
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
            /** Exam Id */
            exam_id: number;
            /** Exam Title */
            exam_title: string;
            /** Status */
            status: string;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Time Spent */
            time_spent: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Submit Time */
            submit_time?: string | null;
        };
        /** AdminResponse */
        AdminResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_import_questions_excel_api_v1_admin_questions_import_post */
        Body_import_questions_excel_api_v1_admin_questions_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_file_api_v1_admin_upload_post */
        Body_upload_file_api_v1_admin_upload_post: {
            /** File */
            file: string;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /**
             * Name
             * @description 分类名称
             */
            name: string;
            /**
             * Icon
             * @description 分类图标标识
             * @default folder
             */
            icon: string | null;
            /**
             * Sort Order
             * @description 排序
             * @default 0
             */
            sort_order: number | null;
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Icon
             * @default folder
             */
            icon: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            /** Icon */
            icon?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** ExamCreate */
        ExamCreate: {
            /**
             * Title
             * @description 试卷标题
             */
            title: string;
            /**
             * Category Id
             * @description 分类ID
             */
            category_id?: number | null;
            /**
             * Cover Url
             * @description 封面图片路径
             * @default
             */
            cover_url: string | null;
            /**
             * Is Timed
             * @description 是否限时
             * @default true
             */
            is_timed: boolean;
            /**
             * Time Limit
             * @description 做题限制时长(分钟)
             * @default 30
             */
            time_limit: number;
            /**
             * Total Score
             * @description 试卷满分
             * @default 100
             */
            total_score: number;
            /**
             * Pass Score
             * @description 及格线分数
             * @default 60
             */
            pass_score: number;
            /**
             * Is Recommended
             * @description 首页推荐标识
             * @default false
             */
            is_recommended: boolean;
            /**
             * Questions
             * @description 组卷关联题目列表
             * @default []
             */
            questions: components["schemas"]["ExamQuestionConfig"][] | null;
        };
        /** ExamDetailResponse */
        ExamDetailResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Category Id */
            category_id?: number | null;
            /**
             * Cover Url
             * @default
             */
            cover_url: string | null;
            /**
             * Is Timed
             * @default true
             */
            is_timed: boolean;
            /**
             * Time Limit
             * @default 30
             */
            time_limit: number;
            /**
             * Total Score
             * @default 100
             */
            total_score: number;
            /**
             * Pass Score
             * @default 60
             */
            pass_score: number;
            /**
             * Is Recommended
             * @default false
             */
            is_recommended: boolean;
            /**
             * Question Count
             * @default 0
             */
            question_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["QuestionResponse"][];
        };
        /** ExamQuestionConfig */
        ExamQuestionConfig: {
            /**
             * Question Id
             * @description 题目ID
             */
            question_id: number;
            /**
             * Score
             * @description 分值
             * @default 10
             */
            score: number;
            /**
             * Sort Order
             * @description 试卷内部排序
             * @default 0
             */
            sort_order: number;
        };
        /** ExamReportResponse */
        ExamReportResponse: {
            /** Record Id */
            record_id: number;
            /** Exam Id */
            exam_id: number;
            /** Exam Title */
            exam_title: string;
            /** User Id */
            user_id: number;
            /** Status */
            status: string;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Time Spent */
            time_spent: number;
            /** Total Questions */
            total_questions: number;
            /** Correct Count */
            correct_count: number;
            /** Wrong Count */
            wrong_count: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Submit Time */
            submit_time?: string | null;
            /**
             * Questions Analysis
             * @default []
             */
            questions_analysis: components["schemas"]["QuestionAnalysisItem"][];
        };
        /** ExamResponse */
        ExamResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Category Id */
            category_id?: number | null;
            /**
             * Cover Url
             * @default
             */
            cover_url: string | null;
            /**
             * Is Timed
             * @default true
             */
            is_timed: boolean;
            /**
             * Time Limit
             * @default 30
             */
            time_limit: number;
            /**
             * Total Score
             * @default 100
             */
            total_score: number;
            /**
             * Pass Score
             * @default 60
             */
            pass_score: number;
            /**
             * Is Recommended
             * @default false
             */
            is_recommended: boolean;
            /**
             * Question Count
             * @default 0
             */
            question_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExamStartRequest */
        ExamStartRequest: {
            /**
             * Exam Id
             * @description 试卷ID
             */
            exam_id: number;
        };
        /** ExamStartResponse */
        ExamStartResponse: {
            /**
             * Record Id
             * @description 答题记录ID
             */
            record_id: number;
            /** Exam Id */
            exam_id: number;
            /** Exam Title */
            exam_title: string;
            /** Is Timed */
            is_timed: boolean;
            /** Time Limit */
            time_limit: number;
            /** Total Score */
            total_score: number;
            /** Pass Score */
            pass_score: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Questions */
            questions: components["schemas"]["QuestionResponse"][];
        };
        /** ExamSubmitRequest */
        ExamSubmitRequest: {
            /**
             * Record Id
             * @description 答题记录ID
             */
            record_id: number;
            /**
             * User Answers
             * @description 作答答案 JSON { 'question_id': ['A'] }
             */
            user_answers: {
                [key: string]: string[];
            };
            /**
             * Time Spent
             * @description 做题消耗时长 (秒)
             * @default 0
             */
            time_spent: number;
        };
        /** ExamUpdate */
        ExamUpdate: {
            /** Title */
            title?: string | null;
            /** Category Id */
            category_id?: number | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Is Timed */
            is_timed?: boolean | null;
            /** Time Limit */
            time_limit?: number | null;
            /** Total Score */
            total_score?: number | null;
            /** Pass Score */
            pass_score?: number | null;
            /** Is Recommended */
            is_recommended?: boolean | null;
            /** Questions */
            questions?: components["schemas"]["ExamQuestionConfig"][] | null;
        };
        /** FavoriteRequest */
        FavoriteRequest: {
            /**
             * Question Id
             * @description 题目ID
             */
            question_id: number;
        };
        /** FavoriteResponse */
        FavoriteResponse: {
            /** Id */
            id: number;
            /** Question Id */
            question_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            question?: components["schemas"]["QuestionResponse"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Username
             * @description 用户名
             */
            username: string;
            /**
             * Password
             * @description 密码
             */
            password: string;
        };
        /** OptionItem */
        OptionItem: {
            /**
             * Key
             * @description 选项标识如 'A', 'B', 'C'
             */
            key: string;
            /**
             * Text
             * @description 选项具体文字描述
             */
            text: string;
        };
        /** PageResponse[AdminExamRecordResponse] */
        PageResponse_AdminExamRecordResponse_: {
            /**
             * Total
             * @description 总记录条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码 (从1开始)
             */
            page: number;
            /**
             * Size
             * @description 每页限制大小
             */
            size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
            /**
             * Has Next
             * @description 是否存在下一页
             */
            has_next: boolean;
            /**
             * Items
             * @description 列表数据项
             */
            items: components["schemas"]["AdminExamRecordResponse"][];
        };
        /** PageResponse[ExamReportResponse] */
        PageResponse_ExamReportResponse_: {
            /**
             * Total
             * @description 总记录条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码 (从1开始)
             */
            page: number;
            /**
             * Size
             * @description 每页限制大小
             */
            size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
            /**
             * Has Next
             * @description 是否存在下一页
             */
            has_next: boolean;
            /**
             * Items
             * @description 列表数据项
             */
            items: components["schemas"]["ExamReportResponse"][];
        };
        /** PageResponse[ExamResponse] */
        PageResponse_ExamResponse_: {
            /**
             * Total
             * @description 总记录条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码 (从1开始)
             */
            page: number;
            /**
             * Size
             * @description 每页限制大小
             */
            size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
            /**
             * Has Next
             * @description 是否存在下一页
             */
            has_next: boolean;
            /**
             * Items
             * @description 列表数据项
             */
            items: components["schemas"]["ExamResponse"][];
        };
        /** PageResponse[FavoriteResponse] */
        PageResponse_FavoriteResponse_: {
            /**
             * Total
             * @description 总记录条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码 (从1开始)
             */
            page: number;
            /**
             * Size
             * @description 每页限制大小
             */
            size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
            /**
             * Has Next
             * @description 是否存在下一页
             */
            has_next: boolean;
            /**
             * Items
             * @description 列表数据项
             */
            items: components["schemas"]["FavoriteResponse"][];
        };
        /** PageResponse[QuestionResponse] */
        PageResponse_QuestionResponse_: {
            /**
             * Total
             * @description 总记录条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码 (从1开始)
             */
            page: number;
            /**
             * Size
             * @description 每页限制大小
             */
            size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
            /**
             * Has Next
             * @description 是否存在下一页
             */
            has_next: boolean;
            /**
             * Items
             * @description 列表数据项
             */
            items: components["schemas"]["QuestionResponse"][];
        };
        /** PageResponse[UserResponse] */
        PageResponse_UserResponse_: {
            /**
             * Total
             * @description 总记录条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码 (从1开始)
             */
            page: number;
            /**
             * Size
             * @description 每页限制大小
             */
            size: number;
            /**
             * Total Pages
             * @description 总页数
             */
            total_pages: number;
            /**
             * Has Next
             * @description 是否存在下一页
             */
            has_next: boolean;
            /**
             * Items
             * @description 列表数据项
             */
            items: components["schemas"]["UserResponse"][];
        };
        /** QuestionAnalysisItem */
        QuestionAnalysisItem: {
            question: components["schemas"]["QuestionResponse"];
            /**
             * User Answer
             * @default []
             */
            user_answer: string[];
            /**
             * Correct Answer
             * @default []
             */
            correct_answer: string[];
            /**
             * Is Correct
             * @default false
             */
            is_correct: boolean;
            /**
             * Is Favorited
             * @default false
             */
            is_favorited: boolean;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /**
             * Type
             * @description 题型: single(单选), multiple(多选), judge(判断), fill(填空)
             */
            type: string;
            /**
             * Title
             * @description 题目题干说明
             */
            title: string;
            /**
             * Options
             * @description 选项列表
             * @default []
             */
            options: components["schemas"]["OptionItem"][] | null;
            /**
             * Answer
             * @description 标准答案列表，例 ['A']
             */
            answer: string[];
            /**
             * Explanation
             * @description 文字详细解析
             * @default
             */
            explanation: string | null;
            /**
             * Difficulty
             * @description 难度: easy, medium, hard
             * @default medium
             */
            difficulty: string | null;
            /**
             * Category Id
             * @description 所属分类ID
             */
            category_id?: number | null;
        };
        /** QuestionResponse */
        QuestionResponse: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /**
             * Options
             * @default []
             */
            options: {
                [key: string]: unknown;
            }[] | null;
            /** Answer */
            answer: string[];
            /**
             * Explanation
             * @default
             */
            explanation: string | null;
            /**
             * Difficulty
             * @default medium
             */
            difficulty: string;
            /** Category Id */
            category_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** QuestionUpdate */
        QuestionUpdate: {
            /** Type */
            type?: string | null;
            /** Title */
            title?: string | null;
            /** Options */
            options?: components["schemas"]["OptionItem"][] | null;
            /** Answer */
            answer?: string[] | null;
            /** Explanation */
            explanation?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Category Id */
            category_id?: number | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Username
             * @description 用户名
             */
            username: string;
            /**
             * Password
             * @description 密码
             */
            password: string;
        };
        /** ResponseModel[AdminResponse] */
        ResponseModel_AdminResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["AdminResponse"] | null;
        };
        /** ResponseModel[CategoryResponse] */
        ResponseModel_CategoryResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["CategoryResponse"] | null;
        };
        /** ResponseModel[ExamDetailResponse] */
        ResponseModel_ExamDetailResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["ExamDetailResponse"] | null;
        };
        /** ResponseModel[ExamReportResponse] */
        ResponseModel_ExamReportResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["ExamReportResponse"] | null;
        };
        /** ResponseModel[ExamStartResponse] */
        ResponseModel_ExamStartResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["ExamStartResponse"] | null;
        };
        /** ResponseModel[FavoriteResponse] */
        ResponseModel_FavoriteResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["FavoriteResponse"] | null;
        };
        /** ResponseModel[List[CategoryResponse]] */
        ResponseModel_List_CategoryResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /**
             * Data
             * @description 业务载荷数据
             */
            data?: components["schemas"]["CategoryResponse"][] | null;
        };
        /** ResponseModel[PageResponse[AdminExamRecordResponse]] */
        ResponseModel_PageResponse_AdminExamRecordResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["PageResponse_AdminExamRecordResponse_"] | null;
        };
        /** ResponseModel[PageResponse[ExamReportResponse]] */
        ResponseModel_PageResponse_ExamReportResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["PageResponse_ExamReportResponse_"] | null;
        };
        /** ResponseModel[PageResponse[ExamResponse]] */
        ResponseModel_PageResponse_ExamResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["PageResponse_ExamResponse_"] | null;
        };
        /** ResponseModel[PageResponse[FavoriteResponse]] */
        ResponseModel_PageResponse_FavoriteResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["PageResponse_FavoriteResponse_"] | null;
        };
        /** ResponseModel[PageResponse[QuestionResponse]] */
        ResponseModel_PageResponse_QuestionResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["PageResponse_QuestionResponse_"] | null;
        };
        /** ResponseModel[PageResponse[UserResponse]] */
        ResponseModel_PageResponse_UserResponse__: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["PageResponse_UserResponse_"] | null;
        };
        /** ResponseModel[QuestionResponse] */
        ResponseModel_QuestionResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["QuestionResponse"] | null;
        };
        /** ResponseModel[TokenResponse] */
        ResponseModel_TokenResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["TokenResponse"] | null;
        };
        /** ResponseModel[UserResponse] */
        ResponseModel_UserResponse_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /** @description 业务载荷数据 */
            data?: components["schemas"]["UserResponse"] | null;
        };
        /** ResponseModel[dict] */
        ResponseModel_dict_: {
            /**
             * Code
             * @description 状态码 200 为成功
             * @default 200
             */
            code: number;
            /**
             * Message
             * @description 提示文本说明
             * @default success
             */
            message: string;
            /**
             * Data
             * @description 业务载荷数据
             */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /**
             * Token
             * @description JWT Bearer Token
             */
            token: string;
            user?: components["schemas"]["UserResponse"] | null;
            admin?: components["schemas"]["AdminResponse"] | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Avatar
             * @default
             */
            avatar: string | null;
            /**
             * Status
             * @default true
             */
            status: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_user_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_UserResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_user_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_api_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_List_CategoryResponse__"];
                };
            };
        };
    };
    list_exams_api_v1_exams_get: {
        parameters: {
            query?: {
                /** @description 分类ID */
                category_id?: number | null;
                /** @description 是否首页推荐 */
                is_recommended?: boolean | null;
                /** @description 页码 */
                page?: number;
                /** @description 每页条数 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_ExamResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_detail_api_v1_exams__exam_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ExamDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_exam_api_v1_records_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ExamStartResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_exam_api_v1_records_submit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ExamReportResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_report_api_v1_records__record_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ExamReportResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exam_history_api_v1_records_history_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_ExamReportResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_v1_favorites_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_FavoriteResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_api_v1_favorites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_FavoriteResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_v1_favorites__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_admin_api_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_TokenResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    init_super_admin_api_v1_admin_auth_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_AdminResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_v1_admin_questions_get: {
        parameters: {
            query?: {
                /** @description 题型过滤 */
                type?: string | null;
                /** @description 分类过滤 */
                category_id?: number | null;
                /** @description 标题关键字 */
                keyword?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_QuestionResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_v1_admin_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_QuestionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_question_api_v1_admin_questions__question_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_QuestionResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_api_v1_admin_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_questions_excel_api_v1_admin_questions_import_post: {
        parameters: {
            query?: {
                category_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_questions_excel_api_v1_admin_questions_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_exams_api_v1_admin_exams_get: {
        parameters: {
            query?: {
                category_id?: number | null;
                keyword?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_ExamResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exam_api_v1_admin_exams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ExamDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exam_api_v1_admin_exams__exam_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_ExamDetailResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_exam_api_v1_admin_exams__exam_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exam_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_admin_categories_api_v1_admin_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_List_CategoryResponse__"];
                };
            };
        };
    };
    create_category_api_v1_admin_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CategoryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_v1_admin_categories__category_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_CategoryResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_v1_admin_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_UserResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_records_api_v1_admin_users_records_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_PageResponse_AdminExamRecordResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_v1_admin_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_admin_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseModel_dict_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
